# Um dockerfile deve sempre começar importando a imagem base.
# Usamos a palavra-chave 'FROM' para fazer isso.
# Em nosso exemplo, queremos importar a imagem python.
# Então escrevemos 'python' para o nome da imagem e 'latest' para a versão.
FROM python:mais recente

# Para iniciar nosso código python, devemos importá-lo para nossa imagem.
# Usamos a palavra-chave 'COPY' para fazer isso.
# O primeiro parâmetro 'main.py' é o nome do arquivo no host.
# O segundo parâmetro '/' é o caminho onde colocar o arquivo na imagem.
# Aqui colocamos o arquivo na pasta raiz da imagem.
COPY main.py /

# Precisamos definir o comando para iniciar quando vamos executar a imagem.
# Usamos a palavra-chave 'CMD' para fazer isso.
# O seguinte comando executará "python ./main.py".
CMD ["python", "./main.py"]